### ISSUE TITLE
What do we actually mean by "pos" and "neg" comments

### ISSUE THREAD

**Issue by sjhermanek** [markegge/monument-comments#10]
We might want to be very careful about our definition here.
E.g., what would we want the following comment be labeled as?
`[...] In response to the proposed rescindment of the Bears Ears monument I wish to express my support for this action. [...]
`

**Comment by markegge** [comment]
This columns show how many template sentences the comment matches against. The template sentences, in turn, are labelled as positive or negative. A comment which matches against five positive template sentences would have a 'pos' value of 5 and 'neg' value of 0. In turn, for comments labelled based on template content, the comment is assigned as positive if it has a positive value in the 'pos' column and negative if there is a positive value in the 'neg' column (I didn't find any instances in which a comment had both positive and negative sentences).
